#!/bin/bash  
#
# -----------------------------------------------------------------------
# ::::      Installing necessary files for the AdminLTE template     ::::
# ::::           https://github.com/foxfher/ses_adminlte.git         ::::
# ::::      (c) 2019 Fernando Bello Mota <fbello04@hotmail.com>      ::::
# -----------------------------------------------------------------------
#


echo "-----------------------------------------------------------------------"
echo "::::      Installing necessary files for the AdminLTE template     ::::"
echo "::::           https://github.com/foxfher/ses_adminlte.git         ::::"
echo "::::      (c) 2019 Fernando Bello Mota <fbello04@hotmail.com>      ::::"
echo "-----------------------------------------------------------------------"
echo ":::: Clonando AdminLTE ::::"
git clone -b v3-dev https://github.com/ColorlibHQ/AdminLTE.git
cd AdminLTE
git clone https://github.com/foxfher/ses_adminlte.git
npm install   
echo ":::: Obteniendo archivos necesarios ::::"
node ses_adminlte/npm/InstallPublish.js -v
cd ..
perl -pi -e "s[~bootstrap/scss/][bootstrap/]g" src/scss/AdminLTE.scss
mv  src/js/base/core/core/AdminLTE.js src/js/base/core/AdminLTE.js
perl -pi -e "s[./][./core/" src/js/base/core/AdminLTE.js
echo ":::: Eliminando AdminLTE ::::"
rm -rf AdminLTE
#rm -rf ses_adminlte